[target]
family = "wasm"
os-name = "wasi"
env-name = "p1"

[backend.c]
variant = "gnu"
target = "wasm32-wasip1"
emulate-i128 = true
compiler-opts = ["--target=wasm32-wasip1", "-Iwasi-shims", "-fno-exceptions", "-Wl,--initial-memory=16777216", "-Wl,--max-memory=268435456"]
linker-opts-post = ["wasi-shims/unwind.o"]

[arch]
name = "wasm32"
pointer-bits = 32
is-big-endian = false
has-atomic-u8 = true
has-atomic-u16 = true
has-atomic-u32 = true
has-atomic-u64 = false
has-atomic-ptr = true
